name: CI

on: [pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn lint
        run: yarn lint
      - name: yarn build
        run: yarn build